# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  workflow_dispatch:

permissions:
  contents: write
  discussions: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Install system dependencies
      run:  sudo apt update && sudo apt install -y ca-certificates curl wget git
    - name: Clone
      run: |
        git clone https://gitee.com/flowerbirds/Dubhe.git
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      working-directory: ./Dubhe/dubhe-server
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      working-directory: ./Dubhe/dubhe-server
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
